WindowsACI running correctly in local without too many intergration
simular-ai/Agent-S pull request #24
Opened 2024-11-26 03:56 UTC by yuhengcai1

Having a lot all functions in WindowsACI that works the same as the MacOSACI, and can be running local test within WindowsACI by itself. Tht ipyny files are used to test in first or by person.

2024-12-21 11:59 UTC, alckasoc commented
Hey @yuhengcai1 , what's the purpose of having the `WindowsACI.py` and the `WindowsOSACI.py`? I notice they have different functions, but it seems you tested only 1 of them in the `testWindows.py` file and notebook.

2024-12-22 12:40 UTC, alckasoc requested changes
I tested the functions with your provided test cases and also the actions that you didn't test. LGTM. 😄 

**Some minor changes:**
- unnecessary imports
- clean up (remove test file, and notebook; they LGTM!)
- "control" -> "ctrl"; not sure about this...is "control" working on your end?

2024-12-22 12:40 UTC, alckasoc commented on agent_s/aci/windowsOSACI.py
> +
For me, "ctrl" works and not "control".

```suggestion
def _normalize_key(key: str) -> str:
    """Convert 'ctrl' to 'control' for pyautogui compatibility"""
    return 'ctrl' if key == 'control' else key
```

Or, if we assume the LLM can consistently generate "ctrl", we can just delete this. Do we need anything  for the FN, Windows, and Alt keys?

EDIT: Nvm, I think it may just be the control key.

2024-12-22 12:40 UTC, alckasoc commented on agent_s/aci/windowsOSACI.py
> +import time
```suggestion
```

2024-12-22 12:40 UTC, alckasoc commented on agent_s/aci/windowsOSACI.py
> +from pywinauto import Desktop, Application
```suggestion
from pywinauto import Desktop
```

2024-12-22 12:57 UTC, yuhengcai1 commented on agent_s/aci/windowsOSACI.py
> +
Thank you, I am looking into it, and I am thinking about changing the cli_app.py to do more testing for intergration.

2024-12-31 13:06 UTC, alckasoc commented
Hey @yuhengcai1 , is there anything more to add to the PR? Other than that, I think the clean-up + the suggestion earlier in the conversation is all that's left before merging.

> I tested the functions with your provided test cases and also the actions that you didn't test. LGTM. 😄
> 
> **Some minor changes:**
> 
> * unnecessary imports
> * clean up (remove test file, and notebook; they LGTM!)
> * "control" -> "ctrl"; not sure about this...is "control" working on your end?

2024-12-31 23:12 UTC, alckasoc commented on agent_s/aci/WindowsACI.py
> +    """Convert 'ctrl' to 'control' for pyautogui compatibility"""
```suggestion
    """Convert 'control' to 'ctrl' for pyautogui compatibility"""
```

2025-01-01 07:33 UTC, alckasoc commented on agent_s/aci/windowsOSACI.py
> +    return 'control' if key == 'ctrl' else key
```suggestion
```

2025-01-01 07:35 UTC, merged